[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python manage.py migrate --settings=config.settings_production && python manage.py collectstatic --noinput --settings=config.settings_production && gunicorn --bind 0.0.0.0:$PORT config.wsgi:application"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.env]
NIXPACKS_PYTHON_VERSION = "3.11"

[deploy.env]
DJANGO_SETTINGS_MODULE = "config.settings_production"
