# Generated by Django 5.2.4 on 2025-08-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('issuer', models.CharField(max_length=200, verbose_name='Организация')),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='ID сертификата')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Дата истечения')),
                ('certificate_image', models.ImageField(upload_to='certificates/', verbose_name='Изображение сертификата')),
                ('verify_url', models.URLField(blank=True, verbose_name='Ссылка для проверки')),
                ('certificate_file', models.FileField(blank=True, upload_to='certificates/files/', verbose_name='Файл сертификата')),
                ('certificate_type', models.CharField(choices=[('course', 'Курс'), ('certification', 'Сертификация'), ('diploma', 'Диплом'), ('achievement', 'Достижение')], max_length=20, verbose_name='Тип сертификата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('skills_learned', models.TextField(help_text='Перечислите через запятую', verbose_name='Изученные навыки')),
                ('score', models.CharField(blank=True, help_text='Например: 100%, A+, 5.0', max_length=20, verbose_name='Оценка')),
                ('has_distinction', models.BooleanField(default=False, verbose_name='С отличием')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-issue_date', 'order'],
            },
        ),
    ]
