# Generated by Django 5.2.4 on 2025-08-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='skills_learned',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='title',
        ),
        migrations.AddField(
            model_name='certificate',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='description_he',
            field=models.TextField(blank=True, verbose_name='Описание (HE)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Описание (RU)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='skills_learned_en',
            field=models.TextField(blank=True, help_text='Перечислите через запятую', verbose_name='Изученные навыки (EN)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='skills_learned_he',
            field=models.TextField(blank=True, help_text='Перечислите через запятую', verbose_name='Изученные навыки (HE)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='skills_learned_ru',
            field=models.TextField(blank=True, help_text='Перечислите через запятую', verbose_name='Изученные навыки (RU)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_en',
            field=models.CharField(default='Certificate Title', max_length=200, verbose_name='Название (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_he',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (HE)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (RU)'),
        ),
    ]
