# Generated by Django 5.2.4 on 2025-08-06 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter')),
                ('working_hours_en', models.CharField(blank=True, max_length=100, verbose_name='Рабочие часы (EN)')),
                ('working_hours_ru', models.CharField(blank=True, max_length=100, verbose_name='Рабочие часы (RU)')),
                ('working_hours_he', models.CharField(blank=True, max_length=100, verbose_name='Рабочие часы (HE)')),
                ('is_available_for_work', models.BooleanField(default=True, verbose_name='Доступен для работы')),
                ('availability_note_en', models.TextField(blank=True, verbose_name='Заметка о доступности (EN)')),
                ('availability_note_ru', models.TextField(blank=True, verbose_name='Заметка о доступности (RU)')),
                ('availability_note_he', models.TextField(blank=True, verbose_name='Заметка о доступности (HE)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Компания')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('read', 'Прочитано'), ('replied', 'Отвечено'), ('archived', 'Архивировано')], default='new', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=20, verbose_name='Приоритет')),
                ('source', models.CharField(default='website', help_text='Откуда пришло сообщение', max_length=50, verbose_name='Источник')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('reply_message', models.TextField(blank=True, verbose_name='Ответ')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
    ]
