# Generated by Django 5.2.4 on 2025-08-06 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('location', models.CharField(default='Israel', max_length=100, verbose_name='Местоположение')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('current_title_en', models.CharField(max_length=200, verbose_name='Должность (EN)')),
                ('current_title_ru', models.CharField(max_length=200, verbose_name='Должность (RU)')),
                ('current_title_he', models.CharField(max_length=200, verbose_name='Должность (HE)')),
                ('bio_en', models.TextField(verbose_name='Описание (EN)')),
                ('bio_ru', models.TextField(verbose_name='Описание (RU)')),
                ('bio_he', models.TextField(verbose_name='Описание (HE)')),
                ('years_management', models.IntegerField(default=20, verbose_name='Лет управленческого опыта')),
                ('years_it', models.IntegerField(default=2, verbose_name='Лет в IT')),
                ('team_size_managed', models.IntegerField(default=40, verbose_name='Размер управляемой команды')),
                ('photo', models.ImageField(blank=True, upload_to='profile/photos/', verbose_name='Фото профиля')),
                ('resume_en', models.FileField(blank=True, upload_to='profile/resumes/', verbose_name='Резюме (EN)')),
                ('resume_ru', models.FileField(blank=True, upload_to='profile/resumes/', verbose_name='Резюме (RU)')),
                ('resume_he', models.FileField(blank=True, upload_to='profile/resumes/', verbose_name='Резюме (HE)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('position_en', models.CharField(max_length=200, verbose_name='Должность (EN)')),
                ('position_ru', models.CharField(max_length=200, verbose_name='Должность (RU)')),
                ('position_he', models.CharField(max_length=200, verbose_name='Должность (HE)')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущая работа')),
                ('description_en', models.TextField(verbose_name='Описание (EN)')),
                ('description_ru', models.TextField(verbose_name='Описание (RU)')),
                ('description_he', models.TextField(verbose_name='Описание (HE)')),
                ('experience_type', models.CharField(choices=[('management', 'Управление'), ('it', 'IT'), ('education', 'Образование')], max_length=20, verbose_name='Тип опыта')),
                ('location', models.CharField(max_length=100, verbose_name='Местоположение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='core.profile')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
                'ordering': ['-start_date', 'order'],
            },
        ),
    ]
