# Generated by Django 4.2.11 on 2025-08-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='position_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='position_he',
            new_name='title_he',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='position_ru',
            new_name='title_ru',
        ),
    ]
