# Generated by Django 5.2.4 on 2025-08-06 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (EN)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (RU)')),
                ('name_he', models.CharField(max_length=100, verbose_name='Название (HE)')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (EN)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('description_he', models.TextField(blank=True, verbose_name='Описание (HE)')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Категория блога',
                'verbose_name_plural': 'Категории блога',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
                ('color', models.CharField(default='#6B7280', max_length=7, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Тег блога',
                'verbose_name_plural': 'Теги блога',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок (EN)')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (RU)')),
                ('title_he', models.CharField(max_length=200, verbose_name='Заголовок (HE)')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
                ('subtitle_en', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок (EN)')),
                ('subtitle_ru', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок (RU)')),
                ('subtitle_he', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок (HE)')),
                ('excerpt_en', models.TextField(max_length=500, verbose_name='Краткое описание (EN)')),
                ('excerpt_ru', models.TextField(max_length=500, verbose_name='Краткое описание (RU)')),
                ('excerpt_he', models.TextField(max_length=500, verbose_name='Краткое описание (HE)')),
                ('content_en', models.TextField(verbose_name='Контент (EN)')),
                ('content_ru', models.TextField(verbose_name='Контент (RU)')),
                ('content_he', models.TextField(verbose_name='Контент (HE)')),
                ('thumbnail', models.ImageField(blank=True, upload_to='blog/thumbnails/', verbose_name='Миниатюра')),
                ('cover_image', models.ImageField(blank=True, upload_to='blog/covers/', verbose_name='Обложка')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'Архивирован')], default='draft', max_length=20, verbose_name='Статус')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('meta_description_en', models.CharField(blank=True, max_length=160, verbose_name='Meta описание (EN)')),
                ('meta_description_ru', models.CharField(blank=True, max_length=160, verbose_name='Meta описание (RU)')),
                ('meta_description_he', models.CharField(blank=True, max_length=160, verbose_name='Meta описание (HE)')),
                ('read_time', models.IntegerField(default=5, verbose_name='Время чтения (мин)')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('categories', models.ManyToManyField(blank=True, to='blog.blogcategory', verbose_name='Категории')),
                ('tags', models.ManyToManyField(blank=True, to='blog.blogtag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Пост блога',
                'verbose_name_plural': 'Посты блога',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
