# Generated by Django 4.2.11 on 2025-08-11 17:06

import apps.blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeepAlive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_ping', models.DateTimeField(auto_now=True, verbose_name='Последний пинг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('ping_count', models.IntegerField(default=0, verbose_name='Количество пингов')),
            ],
            options={
                'verbose_name': 'Keep Alive',
                'verbose_name_plural': 'Keep Alive',
            },
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(default=apps.blog.models.get_default_author, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='Контент (EN)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_he',
            field=models.TextField(blank=True, verbose_name='Контент (HE)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_ru',
            field=models.TextField(blank=True, verbose_name='Контент (RU)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt_en',
            field=models.TextField(blank=True, max_length=500, verbose_name='Краткое описание (EN)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt_he',
            field=models.TextField(blank=True, max_length=500, verbose_name='Краткое описание (HE)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt_ru',
            field=models.TextField(blank=True, max_length=500, verbose_name='Краткое описание (RU)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_he',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (HE)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (RU)'),
        ),
    ]
