# Generated by Django 5.2.4 on 2025-08-06 08:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (EN)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (RU)')),
                ('name_he', models.CharField(max_length=100, verbose_name='Название (HE)')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('icon', models.CharField(blank=True, help_text='CSS класс иконки', max_length=100, verbose_name='Иконка')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Цвет')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория навыков',
                'verbose_name_plural': 'Категории навыков',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('skill_type', models.CharField(choices=[('technical', 'Технический'), ('soft', 'Гибкий навык'), ('language', 'Язык'), ('tool', 'Инструмент')], default='technical', max_length=20, verbose_name='Тип навыка')),
                ('proficiency_level', models.IntegerField(choices=[(1, 'Начинающий'), (2, 'Базовый'), (3, 'Средний'), (4, 'Продвинутый'), (5, 'Эксперт')], default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Уровень владения')),
                ('proficiency_percentage', models.IntegerField(default=50, help_text='От 0 до 100%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент владения')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (EN)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('description_he', models.TextField(blank=True, verbose_name='Описание (HE)')),
                ('years_of_experience', models.FloatField(default=0.0, verbose_name='Лет опыта')),
                ('last_used', models.DateField(blank=True, null=True, verbose_name='Последнее использование')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Иконка')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='Цвет')),
                ('logo', models.ImageField(blank=True, upload_to='skills/logos/', verbose_name='Логотип')),
                ('is_featured', models.BooleanField(default=True, verbose_name='Показывать на главной')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок в категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('related_certificates', models.ManyToManyField(blank=True, to='certificates.certificate', verbose_name='Связанные сертификаты')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skillcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['category', 'order', '-proficiency_percentage'],
                'unique_together': {('name', 'category')},
            },
        ),
    ]
