# Generated by Django 5.2.4 on 2025-08-06 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (EN)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (RU)')),
                ('name_he', models.CharField(max_length=100, verbose_name='Название (HE)')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория проекта',
                'verbose_name_plural': 'Категории проектов',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
                ('color', models.CharField(default='#3B82F6', help_text='HEX цвет для отображения', max_length=7, verbose_name='Цвет')),
                ('icon', models.CharField(blank=True, help_text='CSS класс иконки', max_length=100, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Название (EN)')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название (RU)')),
                ('title_he', models.CharField(max_length=200, verbose_name='Название (HE)')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
                ('description_en', models.TextField(verbose_name='Краткое описание (EN)')),
                ('description_ru', models.TextField(verbose_name='Краткое описание (RU)')),
                ('description_he', models.TextField(verbose_name='Краткое описание (HE)')),
                ('long_description_en', models.TextField(blank=True, verbose_name='Подробное описание (EN)')),
                ('long_description_ru', models.TextField(blank=True, verbose_name='Подробное описание (RU)')),
                ('long_description_he', models.TextField(blank=True, verbose_name='Подробное описание (HE)')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('demo_url', models.URLField(blank=True, verbose_name='Demo URL')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('thumbnail', models.ImageField(blank=True, upload_to='projects/thumbnails/', verbose_name='Миниатюра')),
                ('cover_image', models.ImageField(blank=True, upload_to='projects/covers/', verbose_name='Обложка')),
                ('project_type', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('fullstack', 'Full-Stack'), ('mobile', 'Mobile'), ('desktop', 'Desktop')], max_length=20, verbose_name='Тип проекта')),
                ('status', models.CharField(choices=[('completed', 'Завершен'), ('in_progress', 'В разработке'), ('live', 'Запущен'), ('archived', 'Архивирован')], default='completed', max_length=20, verbose_name='Статус')),
                ('year', models.IntegerField(verbose_name='Год создания')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.projectcategory', verbose_name='Категория')),
                ('technologies', models.ManyToManyField(blank=True, to='portfolio.technology', verbose_name='Технологии')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-is_featured', '-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Изображение')),
                ('caption_en', models.CharField(blank=True, max_length=200, verbose_name='Подпись (EN)')),
                ('caption_ru', models.CharField(blank=True, max_length=200, verbose_name='Подпись (RU)')),
                ('caption_he', models.CharField(blank=True, max_length=200, verbose_name='Подпись (HE)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Изображение проекта',
                'verbose_name_plural': 'Изображения проектов',
                'ordering': ['order'],
            },
        ),
    ]
